name: "Classroom Autograder – Unit 8.4: Iteration (Guessing Game)"

on:
  push:
  pull_request:

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install test dependencies
        run: |
          npm install --save-dev jest@29 jsdom@21 jest-environment-jsdom@29

      - name: Create Jest setup
        run: |
          cat > jest.setup.cjs <<'EOF'
          const { TextEncoder, TextDecoder } = require('util');
          if (typeof global.TextEncoder === 'undefined') global.TextEncoder = TextEncoder;
          if (typeof global.TextDecoder === 'undefined') global.TextDecoder = TextDecoder;
          EOF

      - name: Create Jest config
        run: |
          cat > jest.config.cjs <<'EOF'
          module.exports = {
            testEnvironment: 'jsdom',
            setupFiles: ['<rootDir>/jest.setup.cjs'],
            testMatch: [
              '**/__tests__/**/*.test.cjs',
              '**/?(*.)+(spec|test).[jt]s?(x)'
            ]
          };
          EOF

      - name: Create Jest tests
        run: |
          mkdir -p __tests__
          cat > __tests__/guessing.test.cjs <<'EOF'
          const fs = require('fs');
          const path = require('path');
          const { JSDOM, VirtualConsole } = require('jsdom');

          function findIndexPath() {
            const candidates = ['index.html', 'public/index.html', 'src/index.html', 'docs/index.html'];
            for (const c of candidates) if (fs.existsSync(c)) return c;
            return null;
          }

          async function wait(ms = 30) {
            return new Promise(res => setTimeout(res, ms));
          }

          async function loadDOM() {
            const indexPath = findIndexPath();
            if (!indexPath) throw new Error("index.html not found");

            const baseDir = path.dirname(path.resolve(indexPath));
            const baseUrl = 'file://' + baseDir.replace(/\\+/g, '/') + '/';
            const vconsole = new VirtualConsole();
            vconsole.on('error', () => {});

            const dom = await JSDOM.fromFile(indexPath, {
              url: baseUrl,
              runScripts: 'dangerously',
              resources: 'usable',
              pretendToBeVisual: true,
              virtualConsole: vconsole
            });

            const { window } = dom;
            Object.defineProperty(window.Math, 'random', { value: () => 0, writable: false });
            window.alert = () => { throw new Error('Use textContent, not alert().'); };
            window.prompt = () => { throw new Error('Use inputs, not prompt().'); };

            await new Promise(res => window.addEventListener('load', res, { once: true }));
            await wait();
            return dom;
          }

          function setValue(window, document, id, val) {
            const el = document.getElementById(id);
            if (!el) return false;
            el.value = String(val);
            return true;
          }

          function textOf(document, id) {
            const el = document.getElementById(id);
            return (el?.textContent || el?.innerText || '').trim();
          }

          function callRun(window) {
            try { window.eval('if (typeof runJS==="function"){ runJS(); }'); } catch {}
            if (typeof window.runJS === 'function') window.runJS();
          }

          describe("Unit 8.4 – Iteration Guessing Game", () => {
            let dom, window, document;

            beforeAll(async () => {
              dom = await loadDOM();
              window = dom.window;
              document = window.document;
            });

            test("has required elements (#guess, #feedback, #tries, #hintList)", () => {
              expect(document.getElementById('guess')).not.toBeNull();
              expect(document.getElementById('feedback')).not.toBeNull();
              expect(document.getElementById('tries')).not.toBeNull();
              expect(document.getElementById('hintList')).not.toBeNull();
            });

            test("does not use prompt/alert (uses inputs + textContent)", () => {
              expect(true).toBe(true);
            });

            test("invalid input shows an 'invalid' message in #feedback", async () => {
              expect(setValue(window, document, 'guess', 'abc')).toBe(true);
              callRun(window);
              await wait();
              const fb = textOf(document, 'feedback').toLowerCase();
              expect(fb).toMatch(/invalid/);
            });

            test("selection logic: too high / too low / win (seeded answer=1)", async () => {
              expect(setValue(window, document, 'guess', 10)).toBe(true);
              callRun(window);
              await wait();
              let fb = textOf(document, 'feedback').toLowerCase();
              expect(fb).toMatch(/high/);

              expect(setValue(window, document, 'guess', 0)).toBe(true);
              callRun(window);
              await wait();
              fb = textOf(document, 'feedback').toLowerCase();
              expect(fb).toMatch(/low|invalid/);

              expect(setValue(window, document, 'guess', 1)).toBe(true);
              callRun(window);
              await wait();
              fb = textOf(document, 'feedback').toLowerCase();
              expect(fb).toMatch(/win|correct|you.*got/i);
            });

            test("tries counter increments across multiple guesses", async () => {
              const getNum = s => Number((s.match(/\\d+/) || [0])[0]);
              const start = getNum(textOf(document, 'tries'));
              expect(setValue(window, document, 'guess', 5)).toBe(true);
              callRun(window);
              await wait();
              const mid = getNum(textOf(document, 'tries'));
              expect(mid).toBeGreaterThan(start);
              expect(setValue(window, document, 'guess', 1)).toBe(true);
              callRun(window);
              await wait();
              const after = getNum(textOf(document, 'tries'));
              expect(after).toBeGreaterThan(mid);
            });

            test("for-loop task: #hintList shows numbers 1..10", () => {
              const el = document.getElementById('hintList');
              const items = Array.from(el?.children || []);
              const text = (el?.textContent || '').trim();
              const found = (text.match(/\\b(?:10|[1-9])\\b/g) || []).length >= 10;
              expect(items.length >= 10 || found).toBe(true);
            });
          });
          EOF

      - name: Run tests
        id: jest
        continue-on-error: true
        run: npx jest --runInBand --json --outputFile=jest-results.json

      - name: Upload raw results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jest-results
          path: jest-results.json

      - name: Summarize results for students
        if: always()
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const r = JSON.parse(fs.readFileSync('jest-results.json','utf8'));
          const total = r.numTotalTests ?? 0;
          const passed = r.numPassedTests ?? 0;
          const failed = r.numFailedTests ?? 0;
          const all = (r.testResults || []).flatMap(t => t.assertionResults || []);
          const textOf = t => (t.title || t.fullName || '').toLowerCase();
          const passedBy = k => all.some(t => textOf(t).includes(k.toLowerCase()) && t.status === 'passed');
          const checks = [
            {label:'has required elements', key:'has required elements', hint:'Include #guess, #feedback, #tries, #hintList.'},
            {label:'no prompt/alert (uses inputs & textContent)', key:'does not use prompt/alert', hint:'Use input fields, not prompt or alert.'},
            {label:'invalid input handled', key:'invalid input', hint:'Show “invalid” message for out-of-range.'},
            {label:'selection logic works (low/high/win)', key:'selection logic', hint:'Compare guess vs answer and update feedback.'},
            {label:'tries counter increments', key:'tries counter', hint:'Update #tries each valid guess.'},
            {label:'for-loop task complete', key:'for-loop task', hint:'Populate #hintList with 1–10 using a for loop.'}
          ];
          const icon = ok => ok ? '✅' : '❌';
          const out = [];
          out.push(`# Unit 8.4 Autograder Summary`);
          out.push(`**Passed:** ${passed}/${total} · **Failed:** ${failed}\n`);
          out.push(`## What you got right / need to fix`);
          for (const c of checks) {
            const ok = passedBy(c.key);
            out.push(`${icon(ok)} ${c.label}`);
            if (!ok) out.push(`   - Hint: ${c.hint}`);
          }
          out.push(`\n### Reminders`);
          out.push(`- Use input #guess and button calling runJS().`);
          out.push(`- Update feedback via textContent in #feedback and increment #tries.`);
          out.push(`- Use a for loop to fill #hintList with 1–10.`);
          fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, out.join('\n'));
          NODE

      - name: Set job status
        if: always()
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const r = JSON.parse(fs.readFileSync('jest-results.json','utf8'));
          const total = r.numTotalTests ?? 0;
          const failed = r.numFailedTests ?? 0;
          if (failed > 0 || total === 0) process.exit(1);
          NODE
