name: "Classroom Autograder – Unit 8.4: Iteration (Guessing Game)"

on:
  push:
  pull_request:

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install test dependencies
        run: |
          npm install --save-dev jest@29 jsdom@21 jest-environment-jsdom@29

      - name: Create Jest setup
        run: |
          cat > jest.setup.cjs <<'EOF'
          const { TextEncoder, TextDecoder } = require('util');
          if (typeof global.TextEncoder === 'undefined') global.TextEncoder = TextEncoder;
          if (typeof global.TextDecoder === 'undefined') global.TextDecoder = TextDecoder;
          EOF

      - name: Create Jest config
        run: |
          cat > jest.config.cjs <<'EOF'
          module.exports = {
            testEnvironment: 'jsdom',
            setupFiles: ['<rootDir>/jest.setup.cjs'],
            testMatch: [
              '**/__tests__/**/*.test.cjs',
              '**/?(*.)+(spec|test).[jt]s?(x)'
            ]
          };
          EOF

      - name: Create Jest tests
        run: |
          mkdir -p __tests__
          cat > __tests__/guessing.test.cjs <<'EOF'
          const fs = require('fs');
          const path = require('path');
          const { JSDOM, VirtualConsole } = require('jsdom');

          // ---------- helpers ----------
          const wait = (ms=60) => new Promise(r => setTimeout(r, ms));
          const hasDigit = s => /\d/.test(s || '');
          const norm = s => (s || '').toLowerCase();

          function findPath(cands){ for (const p of cands) if (fs.existsSync(p)) return p; return null; }
          function findIndexPath(){ return findPath(['index.html','public/index.html','src/index.html','docs/index.html']); }
          function findScriptPath(){ return findPath(['script.js','public/script.js','src/script.js','docs/script.js']); }

          function textOf(doc,id){ const el = doc.getElementById(id); return (el?.textContent || el?.innerText || '').trim(); }
          function setVal(doc,id,v){ const el = doc.getElementById(id); if (!el) return false; el.value = String(v); return true; }
          function callRun(win){ try { win.eval('if (typeof runJS==="function"){ runJS(); }'); } catch {} if (typeof win.runJS === 'function') win.runJS(); }

          async function loadDOM() {
            const indexPath = findIndexPath();
            const vconsole = new VirtualConsole();
            vconsole.on('error', () => {}); // keep CI tidy

            if (!indexPath) {
              // Create a minimal DOM rather than throwing, so tests run and fail gracefully.
              const dom = new JSDOM('<!doctype html><html><head></head><body></body></html>', {
                url: 'file:///tmp/',
                runScripts: 'dangerously',
                resources: 'usable',
                pretendToBeVisual: true,
                virtualConsole: vconsole
              });
              dom.window.__MISSING_INDEX__ = true;
              // also mark missing script in case
              dom.window.__MISSING_SCRIPT__ = !findScriptPath();
              return dom;
            }

            const baseDir = path.dirname(path.resolve(indexPath));
            const baseUrl = 'file://' + baseDir.replace(/\\+/g,'/') + '/';

            const dom = await JSDOM.fromFile(indexPath, {
              url: baseUrl,
              runScripts: 'dangerously',
              resources: 'usable',
              pretendToBeVisual: true,
              virtualConsole: vconsole
            });

            // Block prompt/alert per assignment rules
            dom.window.alert = () => { throw new Error('Use textContent, not alert().'); };
            dom.window.prompt = () => { throw new Error('Use inputs, not prompt().'); };

            await new Promise(res => dom.window.addEventListener('load', res, { once: true }));
            await wait();
            return dom;
          }

          async function playUntilWin(window, document) {
            // Ensure game is started
            callRun(window);
            await wait();
            let sawHigh = false, sawLow = false;
            let winGuess = null;

            for (let g = 1; g <= 10; g++) {
              setVal(document, 'guess', g);
              callRun(window);
              await wait();
              const f = norm(textOf(document, 'feedback'));
              if (/win|correct|you.*got/.test(f)) { winGuess = g; break; }
              if (f.includes('high')) sawHigh = true;
              if (f.includes('low'))  sawLow  = true;
            }

            return { winGuess, sawHigh, sawLow };
          }

          // ---------- tests ----------
          describe('Unit 8.4 – Iteration Guessing Game', () => {
            let dom, window, document;

            beforeAll(async () => {
              dom = await loadDOM();
              window = dom.window;
              document = window.document;
            });

            test('has required elements (#guess, #feedback, #tries, #hintList) and button', () => {
              if (window.__MISSING_INDEX__) {
                throw new Error('index.html not found (place it at repo root or /public, /src, /docs).');
              }
              expect(document.getElementById('guess')).not.toBeNull();
              expect(document.getElementById('feedback')).not.toBeNull();
              expect(document.getElementById('tries')).not.toBeNull();
              expect(document.getElementById('hintList')).not.toBeNull();
              expect(document.querySelector('button')).not.toBeNull();
            });

            test('input disabled at load; enabled after Start; disabled again after win', async () => {
              if (window.__MISSING_INDEX__) { throw new Error('index.html missing'); }
              const input = document.getElementById('guess');
              expect(input).not.toBeNull();

              // At load -> must be disabled
              expect(input.disabled).toBe(true);

              // Start game -> must enable
              callRun(window);
              await wait();
              expect(input.disabled).toBe(false);

              // Find a winning guess and ensure disabled after win
              const { winGuess } = await playUntilWin(window, document);
              expect(winGuess).not.toBeNull();
              expect(input.disabled).toBe(true);
            });

            test('does not use prompt/alert (uses inputs + textContent)', () => {
              if (window.__MISSING_INDEX__) { throw new Error('index.html missing'); }
              expect(true).toBe(true);
            });

            test('invalid input shows an "invalid" message in #feedback', async () => {
              if (window.__MISSING_INDEX__) { throw new Error('index.html missing'); }
              callRun(window); await wait();
              setVal(document, 'guess', 'abc');
              callRun(window); await wait();
              expect(norm(textOf(document,'feedback'))).toMatch(/invalid/);
            });

            test('selection logic: shows at least one "high" or "low", and a win', async () => {
              if (window.__MISSING_INDEX__) { throw new Error('index.html missing'); }
              const res = await playUntilWin(window, document);
              expect(res.winGuess).not.toBeNull();
              expect(res.sawHigh || res.sawLow).toBe(true);
            });

            test('tries counter updates across valid guesses (format-agnostic)', async () => {
              if (window.__MISSING_INDEX__) { throw new Error('index.html missing'); }
              callRun(window); await wait();
              const triesId = 'tries';
              const startText = textOf(document, triesId);

              // Make a valid guess (1), then continue until win
              setVal(document, 'guess', 1);
              callRun(window); await wait();
              let endText = textOf(document, triesId);

              if (!/win|correct|you.*got/i.test(norm(textOf(document,'feedback')))) {
                for (let g = 2; g <= 10; g++) {
                  setVal(document, 'guess', g);
                  callRun(window); await wait();
                  endText = textOf(document, triesId);
                  if (/win|correct|you.*got/i.test(norm(textOf(document,'feedback')))) break;
                }
              }

              expect(endText).not.toBe(startText);
              expect(hasDigit(endText)).toBe(true);
            });

            test('for-loop task: #hintList shows numbers 1..10 (on start)', async () => {
              if (window.__MISSING_INDEX__) { throw new Error('index.html missing'); }
              callRun(window); await wait();
              const el = document.getElementById('hintList');
              expect(el).not.toBeNull();
              const kids = Array.from(el.children || []);
              const txt = (el.textContent || '').trim();
              const hasTen = kids.length >= 10;
              const found = (txt.match(/\\b(?:10|[1-9])\\b/g) || []).length >= 10;
              expect(hasTen || found).toBe(true);
            });

            test('script.js contains a while loop', () => {
              const p = findScriptPath();
              if (!p) throw new Error('script.js not found (place it at repo root or /public, /src, /docs).');
              const src = fs.readFileSync(p,'utf8');
              expect(/\\bwhile\\s*\\(/.test(src)).toBe(true);
            });
          });
          EOF

      - name: Run tests (always emit a JSON file)
        id: jest
        run: |
          npx jest --runInBand --json --outputFile=jest-results.json || echo '{"numTotalTests":0,"numPassedTests":0,"numFailedTests":0,"testResults":[]}' > jest-results.json

      - name: Upload raw results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jest-results
          path: jest-results.json

      - name: Summarize results for students
        if: always()
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const summaryFile = process.env.GITHUB_STEP_SUMMARY;

          let r = {};
          try { r = JSON.parse(fs.readFileSync('jest-results.json','utf8')); }
          catch { r = { numTotalTests: 0, numPassedTests: 0, numFailedTests: 0, testResults: [] }; }

          const total  = r.numTotalTests ?? 0;
          const passed = r.numPassedTests ?? 0;
          const failed = r.numFailedTests ?? 0;

          const all = (r.testResults || []).flatMap(t => t.assertionResults || []);
          const txt = t => (t.title || t.fullName || '').toLowerCase();
          const ok  = k => all.some(t => txt(t).includes(k.toLowerCase()) && t.status === 'passed');

          const checks = [
            {label:'has required elements', key:'has required elements'},
            {label:'input disabled/enabled/disabled flow', key:'input disabled at load'},
            {label:'no prompt/alert (uses inputs & textContent)', key:'does not use prompt/alert'},
            {label:'invalid input handled', key:'invalid input'},
            {label:'selection logic works (high/low/win)', key:'selection logic'},
            {label:'tries counter updates', key:'tries counter updates'},
            {label:'for-loop task complete', key:'for-loop task'},
            {label:'while loop present in script.js', key:'contains a while loop'}
          ];

          const icon = b => b ? '✅' : '❌';
          const out = [];
          out.push(`# Unit 8.4 Autograder Summary`);
          out.push(`**Passed:** ${passed}/${total} · **Failed:** ${failed}`);
          out.push('');
          out.push(`## What you got right / need to fix`);
          for (const c of checks) {
            const pass = ok(c.key);
            out.push(`${icon(pass)} ${c.label}`);
            if (!pass) {
              const hints = {
                'input disabled/enabled/disabled flow':'Input disabled at load, enabled on Start, disabled again after win.',
                'selection logic works (high/low/win)':'Compare guess vs secret and update feedback.',
                'tries counter updates':'Update #tries on valid guesses.',
                'for-loop task complete':'Populate #hintList with 1–10 using a for loop.'
              };
              if (hints[c.label]) out.push(`   - Hint: ${hints[c.label]}`);
            }
          }
          out.push('');
          out.push('### Reminders');
          out.push('- One button calls runJS(): start → guess → win → reset.');
          out.push('- Input #guess is disabled until start; disabled again after win.');
          out.push('- Use a for loop for #hintList (1..10) and a while loop to keep checking guesses.');
          out.push('- No prompt()/alert(); update the page with textContent.');

          fs.appendFileSync(summaryFile, out.join('\n'));
          NODE

      - name: Set job status
        if: always()
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const r = JSON.parse(fs.readFileSync('jest-results.json','utf8'));
          const total  = r.numTotalTests ?? 0;
          const failed = r.numFailedTests ?? 0;
          // Mark red X if no tests ran or any failed
          if (failed > 0 || total === 0) process.exit(1);
          NODE
